package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Objects;

/**
 * JPA entity representing a futures contract stored in the {@code futures_contract} table.
 *
 * <p>The entity stores static contract metadata, while maintenance margin remains a derived
 * value because it depends on the current market price.
 *
 * <p>The contract uses:
 *
 * <ul>
 *     <li>{@code ticker} as the stable business identifier</li>
 *     <li>{@code contractSize} and {@code contractUnit} to describe the underlying quantity</li>
 *     <li>{@code settlementDate} to describe the maturity/settlement day</li>
 * </ul>
 */
@Entity
@Table(name = "futures_contract")
@Getter
@Setter
public class FuturesContract {

    /**
     * Multiplier used to derive maintenance margin from the current notional value.
     */
    private static final BigDecimal MAINTENANCE_MARGIN_RATE = new BigDecimal("0.10");

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique futures ticker used as the stable business key for imports.
     */
    @Column(name = "ticker", nullable = false, length = 32, unique = true)
    private String ticker;

    /**
     * Human-readable contract name.
     */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Number of physical units covered by the contract.
     */
    @Column(name = "contract_size", nullable = false)
    private Integer contractSize;

    /**
     * Unit used by the contract, for example {@code Kilogram}, {@code Liter}, or {@code Barrel}.
     */
    @Column(name = "contract_unit", nullable = false, length = 32)
    private String contractUnit;

    /**
     * Date when the contract settles.
     */
    @Column(name = "settlement_date", nullable = false)
    private LocalDate settlementDate;

    /**
     * Derives maintenance margin as {@code contractSize * currentPrice * 10%}.
     *
     * <p>Example:
     * if {@code contractSize = 1000} and {@code price = 82.35},
     * the derived maintenance margin is {@code 8235.0000}.
     *
     * @param price current market price per contract unit
     * @return derived maintenance margin
     */
    public BigDecimal calculateMaintenanceMargin(BigDecimal price) {
        return BigDecimal.valueOf(requireContractSize())
                .multiply(requirePrice(price))
                .multiply(MAINTENANCE_MARGIN_RATE);
    }

    /**
     * Ensures that the market price needed for derived calculations is present.
     *
     * @param price current market price
     * @return non-null price
     */
    private BigDecimal requirePrice(BigDecimal price) {
        return Objects.requireNonNull(price, "price must not be null");
    }

    /**
     * Ensures that the contract size needed for derived calculations is present.
     *
     * @return non-null contract size
     */
    private int requireContractSize() {
        return Objects.requireNonNull(contractSize, "contractSize must not be null");
    }
}
