package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.Objects;

/**
 * JPA entity representing one daily historical snapshot for a listing stored in the
 * {@code listing_daily_price_info} table.
 *
 * <p>The entity stores end-of-day price information for one listing and exposes helper methods
 * for derived analytics that are useful in charts and market-history views.
 */
@Entity
@Table(name = "listing_daily_price_info")
@Getter
@Setter
public class ListingDailyPriceInfo {

    /**
     * Scale used when deriving percentage-based values.
     */
    private static final int PERCENT_SCALE = 4;

    /**
     * Constant used to express relative change as a percentage.
     */
    private static final BigDecimal ONE_HUNDRED = new BigDecimal("100");

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Listing this historical record belongs to.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "listing_id", nullable = false)
    private Listing listing;

    /**
     * Trading day represented by this historical snapshot.
     */
    @Column(name = "date", nullable = false)
    private LocalDate date;

    /**
     * Closing or reference price for the given trading day.
     */
    @Column(name = "price", nullable = false, precision = 19, scale = 8)
    private BigDecimal price;

    /**
     * Ask price captured for the given trading day.
     */
    @Column(name = "ask", nullable = false, precision = 19, scale = 8)
    private BigDecimal ask;

    /**
     * Bid price captured for the given trading day.
     */
    @Column(name = "bid", nullable = false, precision = 19, scale = 8)
    private BigDecimal bid;

    /**
     * Absolute day-over-day price change.
     */
    @Column(name = "change", nullable = false, precision = 19, scale = 8)
    private BigDecimal change;

    /**
     * Traded volume for the given day.
     */
    @Column(name = "volume", nullable = false)
    private Long volume;

    /**
     * Derives change percent as {@code (100 * change) / (price - change)}.
     *
     * <p>The denominator represents the previous price implied by the current price and absolute change.
     *
     * @return derived change percent rounded to 4 decimal places
     */
    public BigDecimal calculateChangePercent() {
        BigDecimal currentPrice = requirePrice();
        BigDecimal priceChange = requireChange();
        BigDecimal previousPrice = currentPrice.subtract(priceChange);

        if (previousPrice.signum() == 0) {
            throw new ArithmeticException("price - change must not be zero");
        }

        return ONE_HUNDRED.multiply(priceChange)
                .divide(previousPrice, PERCENT_SCALE, RoundingMode.HALF_UP);
    }

    /**
     * Derives dollar volume as {@code volume * price}.
     *
     * @return derived dollar volume
     */
    public BigDecimal calculateDollarVolume() {
        return BigDecimal.valueOf(requireVolume()).multiply(requirePrice());
    }

    private BigDecimal requirePrice() {
        return Objects.requireNonNull(price, "price must not be null");
    }

    private BigDecimal requireChange() {
        return Objects.requireNonNull(change, "change must not be null");
    }

    private long requireVolume() {
        return Objects.requireNonNull(volume, "volume must not be null");
    }
}
