package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalTime;

/**
 * JPA entity representing a stock exchange stored in the {@code stock_exchange} table.
 * The entity stores exchange metadata, trading hours, and activation status used for
 * local testing or temporary disabling of a specific exchange.
 */
@Entity
@Table(name = "stock_exchange")
@Getter
@Setter
public class StockExchange {

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full display name of the stock exchange.
     */
    @Column(name = "exchange_name", nullable = false, length = 255)
    private String exchangeName;

    /**
     * Short exchange acronym, for example {@code NYSE} or {@code NASDAQ}.
     */
    @Column(name = "exchange_acronym", nullable = false, length = 50)
    private String exchangeAcronym;

    /**
     * Unique MIC code of the exchange.
     */
    @Column(name = "exchange_mic_code", nullable = false, length = 20)
    private String exchangeMICCode;

    /**
     * Country or polity the exchange belongs to.
     */
    @Column(name = "polity", nullable = false, length = 100)
    private String polity;

    /**
     * Default trading currency used by the exchange.
     */
    @Column(name = "currency", nullable = false, length = 100)
    private String currency;

    /**
     * Time zone identifier used by the exchange, for example {@code America/New_York}.
     */
    @Column(name = "time_zone", nullable = false, length = 100)
    private String timeZone;

    /**
     * Regular market opening time.
     */
    @Column(name = "open_time", nullable = false)
    private LocalTime openTime;

    /**
     * Regular market closing time.
     */
    @Column(name = "close_time", nullable = false)
    private LocalTime closeTime;

    /**
     * Pre-market opening time, if the exchange supports pre-market trading.
     */
    @Column(name = "pre_market_open_time")
    private LocalTime preMarketOpenTime;

    /**
     * Pre-market closing time, if the exchange supports pre-market trading.
     */
    @Column(name = "pre_market_close_time")
    private LocalTime preMarketCloseTime;

    /**
     * Post-market opening time, if the exchange supports post-market trading.
     */
    @Column(name = "post_market_open_time")
    private LocalTime postMarketOpenTime;

    /**
     * Post-market closing time, if the exchange supports post-market trading.
     */
    @Column(name = "post_market_close_time")
    private LocalTime postMarketCloseTime;

    /**
     * Toggle used to enable or disable the exchange for testing or operational control.
     */
    @Column(name = "is_active", nullable = false)
    private Boolean isActive;
}
