package com.banka1.stock_service.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * JPA entity representing a stock instrument stored in the {@code stock} table.
 *
 * <p>The persistent state keeps the core instrument metadata, while values that depend on the
 * current market price are derived through helper methods.
 */
@Entity
@Table(name = "stock")
@Getter
@Setter
public class Stock {

    /**
     * Single-share contract size used for spot-equity trading in this domain model.
     */
    public static final int CONTRACT_SIZE = 1;

    /**
     * Multiplier used to derive maintenance margin from the current price.
     */
    private static final BigDecimal MAINTENANCE_MARGIN_RATE = new BigDecimal("0.50");

    /**
     * Technical primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique stock ticker, for example {@code AAPL} or {@code MSFT}.
     */
    @Column(name = "ticker", nullable = false, length = 32, unique = true)
    private String ticker;

    /**
     * Full company or instrument name shown to users.
     */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Total number of issued shares currently outstanding.
     */
    @Column(name = "outstanding_shares", nullable = false)
    private Long outstandingShares;

    /**
     * Dividend yield stored as a decimal value.
     */
    @Column(name = "dividend_yield", nullable = false, precision = 19, scale = 4)
    private BigDecimal dividendYield;

    /**
     * Returns the fixed contract size for this stock instrument.
     *
     * @return contract size, always {@value #CONTRACT_SIZE}
     */
    public int getContractSize() {
        return CONTRACT_SIZE;
    }

    /**
     * Derives maintenance margin as {@code 50% * currentPrice}.
     *
     * @param price current market price used for the calculation
     * @return derived maintenance margin
     */
    public BigDecimal calculateMaintenanceMargin(BigDecimal price) {
        return requirePrice(price).multiply(MAINTENANCE_MARGIN_RATE);
    }

    /**
     * Derives market capitalization as {@code outstandingShares * currentPrice}.
     *
     * @param price current market price used for the calculation
     * @return derived market capitalization
     */
    public BigDecimal calculateMarketCap(BigDecimal price) {
        return requirePrice(price).multiply(BigDecimal.valueOf(outstandingShares));
    }

    private BigDecimal requirePrice(BigDecimal price) {
        return Objects.requireNonNull(price, "price must not be null");
    }
}
